### ISSUE TITLE
Properties may be safely replaced with `padding` shorthand

### ISSUE THREAD

**Issue by probil** [liubich/memory-game#6]
https://github.com/liubich/memory-game/blob/da7188c3c607b72c47a0e10c36526ac98cdef72d/main.css#L8-L11

Use shorhand instead:
```css
.image_in_table {
  padding: 25% 15% 25% 15%;
  /* or even shorter */
  padding: 25% 15%;
}
```
